// Reads ../rules/types/*.json and writes data.js for the prototype.
// Run with: node build.js

const fs = require('fs');
const path = require('path');

const TYPES_DIR = path.join(__dirname, '..', 'rules', 'types');
const OUT = path.join(__dirname, 'data.js');

const files = fs.readdirSync(TYPES_DIR)
  .filter(f => f.endsWith('.json'))
  .sort();

const items = files.map(f =>
  JSON.parse(fs.readFileSync(path.join(TYPES_DIR, f), 'utf8'))
);

const out =
  '// Auto-generated by build.js — do not edit by hand.\n' +
  'window.CATALOG = ' + JSON.stringify(items, null, 2) + ';\n';

fs.writeFileSync(OUT, out);
console.log(`Wrote data.js with ${items.length} item types`);
