// Auto-generated by build.js — do not edit by hand.
window.CATALOG = [
  {
    "id": "caulking",
    "name": "Caulking",
    "category": "Structural and Interior",
    "synonyms": [
      "sealant",
      "caulk",
      "bead"
    ],
    "placeholder_art": "caulking.svg",
    "summary": "Flexible sealant that closes gaps around tubs, sinks, windows, and trim.",
    "education": "Caulk is the first line of defense against water intrusion. It cracks and pulls away over time, especially around tubs and showers where movement and constant moisture stress the seal. Refreshing caulk is cheap; the rot it prevents is expensive.",
    "questions": [
      {
        "id": "location",
        "prompt": "Where is this run of caulk?",
        "type": "free_text"
      },
      {
        "id": "type",
        "prompt": "Type?",
        "type": "choice",
        "options": [
          "silicone",
          "latex/acrylic",
          "polyurethane",
          "unknown"
        ]
      },
      {
        "id": "last_replaced",
        "prompt": "When was it last replaced?",
        "type": "date"
      }
    ],
    "suggested_photos": [
      {
        "id": "current_state",
        "prompt": "Current condition of the bead"
      },
      {
        "id": "any_gaps",
        "prompt": "Any visible gaps, mold, or pulling away"
      }
    ],
    "maintenance": [
      {
        "action": "Inspect for cracks, gaps, or mold",
        "cadence": {
          "frequency": "yearly"
        },
        "cadence_text": "Once a year",
        "why": "Catches small failures before water gets behind the wall or into subfloor."
      },
      {
        "action": "Replace the bead",
        "cadence": {
          "frequency": "every_5_years"
        },
        "cadence_text": "Every 5 years (sooner in showers)",
        "why": "Old caulk shrinks and pulls away even when it still looks fine."
      }
    ],
    "related_types": [
      "bathtub",
      "shower",
      "kitchen-faucet",
      "window"
    ]
  },
  {
    "id": "dishwasher",
    "name": "Dishwasher",
    "category": "Appliances",
    "synonyms": [],
    "placeholder_art": "dishwasher.svg",
    "summary": "Built-in appliance that washes dishes with hot water and detergent.",
    "education": "Most dishwashers run for 10-15 years. Filters at the base trap food and gradually clog spray arms. Door gaskets harden and leak. A monthly cleaning cycle and a yearly hose check go a long way.",
    "questions": [
      {
        "id": "brand",
        "prompt": "Brand?",
        "type": "free_text"
      },
      {
        "id": "install_year",
        "prompt": "Year installed?",
        "type": "free_text"
      }
    ],
    "suggested_photos": [
      {
        "id": "model_label",
        "prompt": "Model and serial label (often on the side of the door when open)"
      },
      {
        "id": "filter",
        "prompt": "The filter at the bottom"
      },
      {
        "id": "door_gasket",
        "prompt": "Door gasket (the rubber seal)"
      }
    ],
    "maintenance": [
      {
        "action": "Clean the bottom filter",
        "cadence": {
          "frequency": "monthly"
        },
        "cadence_text": "Once a month",
        "why": "Trapped food rots and recirculates onto your dishes."
      },
      {
        "action": "Run a cleaning cycle (vinegar or dishwasher cleaner)",
        "cadence": {
          "frequency": "monthly"
        },
        "cadence_text": "Once a month",
        "why": "Clears mineral buildup from spray arms and pump."
      },
      {
        "action": "Inspect door gasket and supply hose",
        "cadence": {
          "frequency": "yearly"
        },
        "cadence_text": "Once a year",
        "why": "Slow leaks at the connection or gasket cause cabinet rot before you notice."
      }
    ],
    "related_types": [
      "garbage-disposal",
      "kitchen-faucet"
    ]
  },
  {
    "id": "dryer-vent",
    "name": "Dryer Vent",
    "category": "Safety and Detection",
    "synonyms": [
      "dryer duct",
      "dryer exhaust"
    ],
    "placeholder_art": "dryer-vent.svg",
    "summary": "Exhausts hot, moist air and lint from the clothes dryer to outside.",
    "education": "Lint accumulates inside the duct over time and is highly flammable. Clogged dryer vents are one of the leading causes of house fires. Long, twisty runs to the outside need cleaning more often than short straight ones.",
    "questions": [
      {
        "id": "run_length",
        "prompt": "Approximate run length?",
        "type": "free_text"
      },
      {
        "id": "exit_location",
        "prompt": "Where does it exit the house?",
        "type": "free_text"
      }
    ],
    "suggested_photos": [
      {
        "id": "interior_connection",
        "prompt": "Where the duct connects to the dryer"
      },
      {
        "id": "exterior_vent",
        "prompt": "Exterior vent hood (with the flap)"
      }
    ],
    "maintenance": [
      {
        "action": "Clean lint from the entire duct run",
        "cadence": {
          "frequency": "yearly"
        },
        "cadence_text": "At least once a year",
        "why": "Lint builds up beyond the lint trap and can ignite from a hot exhaust."
      },
      {
        "action": "Check that the exterior flap opens freely",
        "cadence": {
          "frequency": "twice_yearly"
        },
        "cadence_text": "Twice a year",
        "why": "Stuck flaps trap moist air inside and let pests in."
      }
    ],
    "related_types": [
      "dryer",
      "washing-machine"
    ]
  },
  {
    "id": "fire-extinguisher",
    "name": "Fire Extinguisher",
    "category": "Safety and Detection",
    "synonyms": [],
    "placeholder_art": "fire-extinguisher.svg",
    "summary": "Portable device for putting out small fires before they spread.",
    "education": "Most home extinguishers are dry-chemical ABC units. The pressure gauge tells you if it is still charged. The powder inside can settle and cake if not shaken occasionally. Many have a 6-12 year lifespan from manufacture.",
    "questions": [
      {
        "id": "class",
        "prompt": "Class?",
        "type": "choice",
        "options": [
          "ABC (multipurpose)",
          "K (kitchen)",
          "BC",
          "other",
          "unknown"
        ]
      },
      {
        "id": "manufacture_date",
        "prompt": "Manufacture date (stamped on the bottom or label)?",
        "type": "date"
      },
      {
        "id": "location",
        "prompt": "Where is it kept?",
        "type": "free_text"
      }
    ],
    "suggested_photos": [
      {
        "id": "label",
        "prompt": "Label with class, weight, and manufacture date"
      },
      {
        "id": "gauge",
        "prompt": "Pressure gauge"
      }
    ],
    "maintenance": [
      {
        "action": "Check the pressure gauge",
        "cadence": {
          "frequency": "monthly"
        },
        "cadence_text": "Once a month",
        "why": "If the needle drops out of the green, the unit may not discharge in a fire."
      },
      {
        "action": "Shake or invert to loosen the powder",
        "cadence": {
          "frequency": "yearly"
        },
        "cadence_text": "Once a year",
        "why": "Caked powder can clog the discharge nozzle."
      },
      {
        "action": "Replace the unit",
        "cadence": {
          "frequency": "every_10_years"
        },
        "cadence_text": "Every 10-12 years (or per manufacturer)",
        "why": "Internal parts and seals weaken with age regardless of pressure."
      }
    ],
    "related_types": [
      "smoke-detector",
      "co-detector"
    ]
  },
  {
    "id": "furnace",
    "name": "Furnace",
    "category": "HVAC",
    "synonyms": [
      "forced-air heater",
      "gas furnace",
      "heating system"
    ],
    "placeholder_art": "furnace.svg",
    "summary": "Heats and circulates air through the home's ductwork.",
    "education": "A furnace pulls return air across a heat exchanger and sends it back through the ducts. Routine filter changes and an annual professional inspection extend its life and protect against carbon-monoxide leaks from a cracked heat exchanger.",
    "questions": [
      {
        "id": "fuel",
        "prompt": "Fuel type?",
        "type": "choice",
        "options": [
          "natural gas",
          "propane",
          "oil",
          "electric",
          "other"
        ]
      },
      {
        "id": "age",
        "prompt": "Approximate age?",
        "type": "free_text"
      },
      {
        "id": "last_serviced",
        "prompt": "When was it last professionally serviced?",
        "type": "date"
      }
    ],
    "suggested_photos": [
      {
        "id": "nameplate",
        "prompt": "Nameplate with model and serial number"
      },
      {
        "id": "front",
        "prompt": "Front of the unit"
      },
      {
        "id": "filter_slot",
        "prompt": "Where the filter goes (capture the size)"
      }
    ],
    "maintenance": [
      {
        "action": "Replace the air filter",
        "cadence": {
          "frequency": "quarterly"
        },
        "cadence_text": "Every 1-3 months while running",
        "why": "A clogged filter strains the blower, reduces efficiency, and can overheat the unit."
      },
      {
        "action": "Schedule a professional tune-up",
        "cadence": {
          "frequency": "yearly",
          "preferred_seasons": [
            "fall"
          ]
        },
        "cadence_text": "Once a year, ideally in fall before heating season",
        "why": "Catches cracked heat exchangers, weak ignitors, and clogged burners before failure."
      }
    ],
    "related_types": [
      "hvac-filter",
      "thermostat",
      "ductwork",
      "co-detector"
    ]
  },
  {
    "id": "gutter",
    "name": "Gutter",
    "category": "Roof and Drainage",
    "synonyms": [
      "eavestrough",
      "rain gutter"
    ],
    "placeholder_art": "gutter.svg",
    "summary": "Channels rainwater off the roof and away from the foundation.",
    "education": "Gutters keep roof runoff from soaking into the foundation and basement walls. When they clog or sag, water spills over the edge or sits stagnant, leading to wood rot at the fascia, ice dams in winter, and foundation cracks over time.",
    "questions": [
      {
        "id": "material",
        "prompt": "What material?",
        "type": "choice",
        "options": [
          "aluminum",
          "vinyl",
          "copper",
          "steel",
          "wood",
          "other"
        ]
      },
      {
        "id": "guards",
        "prompt": "Do they have leaf guards?",
        "type": "yes_no"
      },
      {
        "id": "trees_overhead",
        "prompt": "Are there trees overhanging?",
        "type": "yes_no"
      },
      {
        "id": "last_cleaned",
        "prompt": "When were these last cleaned?",
        "type": "date"
      }
    ],
    "suggested_photos": [
      {
        "id": "full_length",
        "prompt": "Full length from the ground"
      },
      {
        "id": "downspout_join",
        "prompt": "Where the downspout meets the gutter"
      },
      {
        "id": "any_damage",
        "prompt": "Sag, rust, or visible damage"
      }
    ],
    "maintenance": [
      {
        "action": "Clean debris",
        "cadence": {
          "frequency": "twice_yearly",
          "preferred_seasons": [
            "spring",
            "fall"
          ]
        },
        "cadence_text": "Twice a year, spring and fall",
        "why": "Clogged gutters overflow against the house and lead to foundation water damage."
      },
      {
        "action": "Inspect for sag, rust, or separation",
        "cadence": {
          "frequency": "yearly",
          "preferred_seasons": [
            "spring"
          ]
        },
        "cadence_text": "Once a year, in spring",
        "why": "Catches loose hangers and pulled-away sections before a heavy rain reveals them."
      }
    ],
    "related_types": [
      "downspout",
      "fascia",
      "soffit",
      "roof"
    ]
  },
  {
    "id": "hvac-filter",
    "name": "HVAC Filter",
    "category": "HVAC",
    "synonyms": [
      "furnace filter",
      "air filter",
      "return filter"
    ],
    "placeholder_art": "hvac-filter.svg",
    "summary": "Disposable filter that traps dust before air enters the furnace or AC.",
    "education": "A clean filter improves efficiency and protects the blower motor and coils from buildup. Higher MERV ratings catch finer particles but restrict airflow more, so pick a rating your system can handle without straining.",
    "questions": [
      {
        "id": "size",
        "prompt": "Filter size (e.g., 16x25x1)?",
        "type": "free_text"
      },
      {
        "id": "merv",
        "prompt": "MERV rating?",
        "type": "free_text"
      },
      {
        "id": "location",
        "prompt": "Where does it go?",
        "type": "free_text"
      }
    ],
    "suggested_photos": [
      {
        "id": "current_filter",
        "prompt": "The filter showing its size printed on the frame"
      },
      {
        "id": "slot",
        "prompt": "Where it slides in"
      }
    ],
    "maintenance": [
      {
        "action": "Replace the filter",
        "cadence": {
          "frequency": "quarterly"
        },
        "cadence_text": "Every 1-3 months while the system runs",
        "why": "A clogged filter strains the blower, raises bills, and lets dust through gaps."
      }
    ],
    "related_types": [
      "furnace",
      "air-conditioner"
    ]
  },
  {
    "id": "smoke-detector",
    "name": "Smoke Detector",
    "category": "Safety and Detection",
    "synonyms": [
      "smoke alarm",
      "fire alarm"
    ],
    "placeholder_art": "smoke-detector.svg",
    "summary": "Detects smoke and sounds an alarm to alert occupants.",
    "education": "Modern smoke detectors are typically replaced every 10 years because the sensor element degrades. Most have a manufacture date stamped on the back. Battery-only, hardwired, and combination smoke/CO units all need regular testing.",
    "questions": [
      {
        "id": "type",
        "prompt": "Type?",
        "type": "choice",
        "options": [
          "battery only",
          "hardwired",
          "hardwired with battery backup",
          "combination smoke/CO"
        ]
      },
      {
        "id": "manufacture_date",
        "prompt": "Manufacture date (often on the back)?",
        "type": "date"
      },
      {
        "id": "location",
        "prompt": "Where is it?",
        "type": "free_text"
      }
    ],
    "suggested_photos": [
      {
        "id": "front",
        "prompt": "Front of the unit"
      },
      {
        "id": "back_label",
        "prompt": "Back label with manufacture date"
      }
    ],
    "maintenance": [
      {
        "action": "Test the alarm",
        "cadence": {
          "frequency": "monthly"
        },
        "cadence_text": "Once a month",
        "why": "Confirms the horn and sensor are working — a dead detector is silent during a fire."
      },
      {
        "action": "Replace the battery",
        "cadence": {
          "frequency": "yearly"
        },
        "cadence_text": "Once a year (or when it chirps)",
        "why": "Even battery backups in hardwired units fail without notice."
      },
      {
        "action": "Replace the entire unit",
        "cadence": {
          "frequency": "every_10_years"
        },
        "cadence_text": "Every 10 years",
        "why": "The sensor element loses sensitivity even if the alarm still chirps."
      }
    ],
    "related_types": [
      "co-detector",
      "fire-extinguisher"
    ]
  },
  {
    "id": "sump-pump",
    "name": "Sump Pump",
    "category": "Plumbing",
    "synonyms": [
      "basement pump",
      "drainage pump"
    ],
    "placeholder_art": "sump-pump.svg",
    "summary": "Pumps groundwater out of the basement sump pit to keep it dry.",
    "education": "Sump pumps fail at the worst possible time — during the heavy rain that triggered them. A backup battery or water-powered backup is what stands between you and a flooded basement when the power goes out.",
    "questions": [
      {
        "id": "primary_type",
        "prompt": "Pump type?",
        "type": "choice",
        "options": [
          "submersible",
          "pedestal"
        ]
      },
      {
        "id": "has_backup",
        "prompt": "Is there a backup pump or battery?",
        "type": "yes_no"
      },
      {
        "id": "install_year",
        "prompt": "Year installed?",
        "type": "free_text"
      }
    ],
    "suggested_photos": [
      {
        "id": "pit",
        "prompt": "Looking down into the sump pit"
      },
      {
        "id": "discharge",
        "prompt": "Discharge pipe where it exits the house"
      },
      {
        "id": "nameplate",
        "prompt": "Pump nameplate with model"
      }
    ],
    "maintenance": [
      {
        "action": "Test by pouring water into the pit",
        "cadence": {
          "frequency": "quarterly"
        },
        "cadence_text": "Every 3 months",
        "why": "A pump that hasn't run in months may seize. Testing ensures it kicks on."
      },
      {
        "action": "Replace the backup battery",
        "cadence": {
          "frequency": "every_5_years"
        },
        "cadence_text": "Every 3-5 years",
        "why": "Sealed lead-acid batteries lose capacity invisibly until the day you need them."
      },
      {
        "action": "Clean debris from the pit",
        "cadence": {
          "frequency": "yearly"
        },
        "cadence_text": "Once a year",
        "why": "Gravel and silt jam the float switch — the most common failure mode."
      }
    ],
    "related_types": [
      "water-heater",
      "basement-floor-drain"
    ]
  },
  {
    "id": "water-heater",
    "name": "Water Heater",
    "category": "Plumbing",
    "synonyms": [
      "hot water heater",
      "hot water tank",
      "water tank"
    ],
    "placeholder_art": "water-heater.svg",
    "summary": "Heats and stores domestic hot water.",
    "education": "Tank-style water heaters typically last 8-12 years. Sediment builds up at the bottom over time, reducing efficiency and capacity. A failing pressure-relief valve or anode rod is far cheaper to replace than the tank itself.",
    "questions": [
      {
        "id": "type",
        "prompt": "Type?",
        "type": "choice",
        "options": [
          "tank gas",
          "tank electric",
          "tankless gas",
          "tankless electric",
          "heat pump",
          "other"
        ]
      },
      {
        "id": "capacity",
        "prompt": "Capacity in gallons (if tank)?",
        "type": "free_text"
      },
      {
        "id": "install_year",
        "prompt": "Year installed?",
        "type": "free_text"
      }
    ],
    "suggested_photos": [
      {
        "id": "nameplate",
        "prompt": "Model and serial nameplate"
      },
      {
        "id": "full",
        "prompt": "Full unit including connections at the top"
      },
      {
        "id": "drain_valve",
        "prompt": "The drain valve at the base"
      }
    ],
    "maintenance": [
      {
        "action": "Flush the tank to clear sediment",
        "cadence": {
          "frequency": "yearly"
        },
        "cadence_text": "Once a year",
        "why": "Sediment insulates the burner from the water, raising bills and shortening the tank's life."
      },
      {
        "action": "Test the pressure-relief valve",
        "cadence": {
          "frequency": "yearly"
        },
        "cadence_text": "Once a year",
        "why": "A stuck valve cannot vent excess pressure, which is a real safety hazard."
      },
      {
        "action": "Check the anode rod",
        "cadence": {
          "frequency": "every_5_years"
        },
        "cadence_text": "Every 3-5 years",
        "why": "The anode corrodes in place of the tank. When it's gone, the tank starts to."
      }
    ],
    "related_types": [
      "sump-pump",
      "main-shutoff"
    ]
  }
];
